services:
  api-service:
    container_name: rest-rest_api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command: ["pnpm", "run", "start:dev"]
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "8080:8080" # HOST_PORT : CONTAINER_PORT
    networks:
      - rest-rest_network
  db:
    container_name: rest-rest_postgres
    image: postgres:16.6
    env_file:
      - ./api/.env
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - rest-rest_network
networks:
  rest-rest_network:
    driver: bridge
