FROM node:22-alpine

# To use pnpm, we need to enable corepack
RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .
RUN pnpm build

EXPOSE 8080 
CMD ["pnpm", "start"]